name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Fix escaped quotes
        run: |
          find frontend -type f \( -name "*.tsx" -o -name "*.ts" -o -name "*.js" -o -name "*.jsx" \) -exec sed -i 's/\\"/"/g' {} +

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Prebuild Android
        working-directory: frontend
        run: npx expo prebuild --platform android --clean

      - name: Build APK
        working-directory: frontend
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qasati-apk
          path: frontend/android/app/build/outputs/apk/release/*.apk
